source 'https://github.com/CocoaPods/Specs.git'

pod "EDHFinder", :path => "../"

target 'EDHFinder' do
end

target 'Tests' do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
